title: Verena Ortlieb
email: verena.ortlieb@gmail.com
description: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://verenaortlieb.com" # the base hostname & protocol for your site

permalinks: pretty

markdown: kramdown

languages: ["en", "de"]

gems:
  - jekyll-language-plugin
  - jekyll-sitemap

language_data: data.lang.%%
language_includes_dir: _i18n

include: [ ".nojekyll", "CNAME" ]

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - Guardfile
  - publi.sh
  - Personal Website.sublime-project
  - Personal Website.sublime-workspace
