title: Verena Ortlieb
permalink: /:title/
base: http://www.verenaortlieb.com

kramdown:
  input: GFM

exclude: [ "Gemfile", "Gemfile.lock", "Makefile" ]

defaults:
  -
    scope:
      path: ""
    values:
      layout: page