permalink: /:title/
url: http://www.verenaortlieb.com

kramdown:
  input: GFM

exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - Readme.md
  - CNAME

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
